export enum EntityType {
    Administrator,
    Authentication,
    Appointment,
    AppointmentRequest,
    AppointmentType,
    BodyMeasurement,
    CancelationRequest,
    ChangeUsername,
    Client,
    Coach,
    FunctionalMovementScreen,
    Product,
    Recipe,
    Role ,
    RecurringAppointment ,
    ResetUserPassword ,
    TimeSlot ,
    User
}
