export enum EntityType {
    Administrator,
    Authentication,
    Appointment,
    AppointmentRequest,
    AppointmentLocation,
    AppointmentType,
    BodyMeasurement,
    CancelationRequest,
    ChangeUsername,
    Client,
    Coach,
    FunctionalMovementScreen,
    Recipe,
    Role ,
    RecurringAppointment ,
    ResetUserPassword ,
    TimeSlot ,
    Training,
    User,
    Workout,
    ClientGoal
}
